// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0D9RFztwVoRAgVubufqJevZ5Tuqy_emY',
    appId: '1:350109907207:web:fdbe8e5a0c1ef5981feda2',
    messagingSenderId: '350109907207',
    projectId: 'fir-new-project-1b08c',
    authDomain: 'fir-new-project-1b08c.firebaseapp.com',
    storageBucket: 'fir-new-project-1b08c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMfaSf0Uqlnfp2QMxguUcrNECOyjGlK6g',
    appId: '1:350109907207:android:ab7b90d83671486c1feda2',
    messagingSenderId: '350109907207',
    projectId: 'fir-new-project-1b08c',
    storageBucket: 'fir-new-project-1b08c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuUVVfk62K6___cULP9IUcOJ7hHIuHjyU',
    appId: '1:350109907207:ios:3dbe288497ae16751feda2',
    messagingSenderId: '350109907207',
    projectId: 'fir-new-project-1b08c',
    storageBucket: 'fir-new-project-1b08c.firebasestorage.app',
    iosBundleId: 'com.example.newfirebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuUVVfk62K6___cULP9IUcOJ7hHIuHjyU',
    appId: '1:350109907207:ios:3dbe288497ae16751feda2',
    messagingSenderId: '350109907207',
    projectId: 'fir-new-project-1b08c',
    storageBucket: 'fir-new-project-1b08c.firebasestorage.app',
    iosBundleId: 'com.example.newfirebaseproject',
  );
}
